version: '3.8'
services:
  node:
    build: 
      context: ./
    container_name: node-app
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    command: npm start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
  nginx:
    image: nginx
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - node
  